/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "C:\\Git\\vuepress-theme-kb\\layouts\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-7832e8be",
    path: "/2018/11/07/frontmatter-in-vuepress-2/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Post", "v-7832e8be").then(next)
    },
  },
  {
    path: "/2018/11/07/frontmatter-in-vuepress-2/index.html",
    redirect: "/2018/11/07/frontmatter-in-vuepress-2/"
  },
  {
    path: "/_posts/2018-11-7-frontmatter-in-vuepress-2.html",
    redirect: "/2018/11/07/frontmatter-in-vuepress-2/"
  },
  {
    name: "v-b07f4888",
    path: "/2018/11/07/frontmatter-in-vuepress-3/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Post", "v-b07f4888").then(next)
    },
  },
  {
    path: "/2018/11/07/frontmatter-in-vuepress-3/index.html",
    redirect: "/2018/11/07/frontmatter-in-vuepress-3/"
  },
  {
    path: "/_posts/2018-11-7-frontmatter-in-vuepress-3.html",
    redirect: "/2018/11/07/frontmatter-in-vuepress-3/"
  },
  {
    name: "v-4638da08",
    path: "/2018/11/07/frontmatter-in-vuepress/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Post", "v-4638da08").then(next)
    },
  },
  {
    path: "/2018/11/07/frontmatter-in-vuepress/index.html",
    redirect: "/2018/11/07/frontmatter-in-vuepress/"
  },
  {
    path: "/_posts/2018-11-7-frontmatter-in-vuepress.html",
    redirect: "/2018/11/07/frontmatter-in-vuepress/"
  },
  {
    name: "v-a250cabc",
    path: "/2019/02/26/markdown-slot-2/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Post", "v-a250cabc").then(next)
    },
  },
  {
    path: "/2019/02/26/markdown-slot-2/index.html",
    redirect: "/2019/02/26/markdown-slot-2/"
  },
  {
    path: "/_posts/2019-2-26-markdown-slot-2.html",
    redirect: "/2019/02/26/markdown-slot-2/"
  },
  {
    name: "v-901caf40",
    path: "/2019/02/26/markdown-slot-3/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Post", "v-901caf40").then(next)
    },
  },
  {
    path: "/2019/02/26/markdown-slot-3/index.html",
    redirect: "/2019/02/26/markdown-slot-3/"
  },
  {
    path: "/_posts/2019-2-26-markdown-slot-3.html",
    redirect: "/2019/02/26/markdown-slot-3/"
  },
  {
    name: "v-7de893c4",
    path: "/2019/02/26/markdown-slot-4/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Post", "v-7de893c4").then(next)
    },
  },
  {
    path: "/2019/02/26/markdown-slot-4/index.html",
    redirect: "/2019/02/26/markdown-slot-4/"
  },
  {
    path: "/_posts/2019-2-26-markdown-slot-4.html",
    redirect: "/2019/02/26/markdown-slot-4/"
  },
  {
    name: "v-2e581418",
    path: "/2019/05/06/writing-a-vuepress-theme-2/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Post", "v-2e581418").then(next)
    },
  },
  {
    path: "/2019/05/06/writing-a-vuepress-theme-2/index.html",
    redirect: "/2019/05/06/writing-a-vuepress-theme-2/"
  },
  {
    path: "/_posts/2019-5-6-writing-a-vuepress-theme-2.html",
    redirect: "/2019/05/06/writing-a-vuepress-theme-2/"
  },
  {
    name: "v-c729b8a8",
    path: "/2019/02/26/markdown-slot/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Post", "v-c729b8a8").then(next)
    },
  },
  {
    path: "/2019/02/26/markdown-slot/index.html",
    redirect: "/2019/02/26/markdown-slot/"
  },
  {
    path: "/_posts/2019-2-26-markdown-slot.html",
    redirect: "/2019/02/26/markdown-slot/"
  },
  {
    name: "v-186168f2",
    path: "/2019/05/06/writing-a-vuepress-theme-3/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Post", "v-186168f2").then(next)
    },
  },
  {
    path: "/2019/05/06/writing-a-vuepress-theme-3/index.html",
    redirect: "/2019/05/06/writing-a-vuepress-theme-3/"
  },
  {
    path: "/_posts/2019-5-6-writing-a-vuepress-theme-3.html",
    redirect: "/2019/05/06/writing-a-vuepress-theme-3/"
  },
  {
    name: "v-47eedbf0",
    path: "/2019/05/06/writing-a-vuepress-theme-4/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Post", "v-47eedbf0").then(next)
    },
  },
  {
    path: "/2019/05/06/writing-a-vuepress-theme-4/index.html",
    redirect: "/2019/05/06/writing-a-vuepress-theme-4/"
  },
  {
    path: "/_posts/2019-5-6-writing-a-vuepress-theme-4.html",
    redirect: "/2019/05/06/writing-a-vuepress-theme-4/"
  },
  {
    name: "v-47b1d5a7",
    path: "/about.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-47b1d5a7").then(next)
    },
  },
  {
    name: "v-69e22104",
    path: "/2019/05/06/writing-a-vuepress-theme/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Post", "v-69e22104").then(next)
    },
  },
  {
    path: "/2019/05/06/writing-a-vuepress-theme/index.html",
    redirect: "/2019/05/06/writing-a-vuepress-theme/"
  },
  {
    path: "/_posts/2019-5-6-writing-a-vuepress-theme.html",
    redirect: "/2019/05/06/writing-a-vuepress-theme/"
  },
  {
    name: "v-b2754d56",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b2754d56").then(next)
    },
    meta: {"pid":"post","id":"post"}
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-b1564aac",
    path: "/tag/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("FrontmatterKey", "v-b1564aac").then(next)
    },
    meta: {"pid":"tag","id":"tag"}
  },
  {
    path: "/tag/index.html",
    redirect: "/tag/"
  },
  {
    name: "v-f8241222",
    path: "/tag/frontmatter/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("FrontmatterPagination", "v-f8241222").then(next)
    },
    meta: {"pid":"tag","id":"frontmatter"}
  },
  {
    path: "/tag/frontmatter/index.html",
    redirect: "/tag/frontmatter/"
  },
  {
    name: "v-dfb71430",
    path: "/tag/vuepress/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("FrontmatterPagination", "v-dfb71430").then(next)
    },
    meta: {"pid":"tag","id":"vuepress"}
  },
  {
    path: "/tag/vuepress/index.html",
    redirect: "/tag/vuepress/"
  },
  {
    name: "v-3ae5b494",
    path: "/tag/markdown/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("FrontmatterPagination", "v-3ae5b494").then(next)
    },
    meta: {"pid":"tag","id":"markdown"}
  },
  {
    path: "/tag/markdown/index.html",
    redirect: "/tag/markdown/"
  },
  {
    name: "v-58f012a0",
    path: "/tag/theme/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("FrontmatterPagination", "v-58f012a0").then(next)
    },
    meta: {"pid":"tag","id":"theme"}
  },
  {
    path: "/tag/theme/index.html",
    redirect: "/tag/theme/"
  },
  {
    name: "v-1559f73a",
    path: "/tag/blog/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("FrontmatterPagination", "v-1559f73a").then(next)
    },
    meta: {"pid":"tag","id":"blog"}
  },
  {
    path: "/tag/blog/index.html",
    redirect: "/tag/blog/"
  },
  {
    name: "v-8fdafa70",
    path: "/page/2/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-8fdafa70").then(next)
    },
    meta: {"pid":"post","id":"post"}
  },
  {
    path: "/page/2/index.html",
    redirect: "/page/2/"
  },
  {
    name: "v-8fdafa32",
    path: "/page/3/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-8fdafa32").then(next)
    },
    meta: {"pid":"post","id":"post"}
  },
  {
    path: "/page/3/index.html",
    redirect: "/page/3/"
  },
  {
    name: "v-c5eeaa56",
    path: "/tag/vuepress/page/2/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c5eeaa56").then(next)
    },
    meta: {"pid":"tag","id":"vuepress"}
  },
  {
    path: "/tag/vuepress/page/2/index.html",
    redirect: "/tag/vuepress/page/2/"
  },
  {
    name: "v-c5eeaa18",
    path: "/tag/vuepress/page/3/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c5eeaa18").then(next)
    },
    meta: {"pid":"tag","id":"vuepress"}
  },
  {
    path: "/tag/vuepress/page/3/index.html",
    redirect: "/tag/vuepress/page/3/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]