/**
 * Generated by "@vuepress/plugin-blog"
 */
export default {
  "tag": {
    "frontmatter": {
      "key": "frontmatter",
      "scope": "tag",
      "path": "/tag/frontmatter/",
      "pageKeys": [
        "v-b07f4888",
        "v-4638da08",
        "v-7832e8be"
      ]
    },
    "vuepress": {
      "key": "vuepress",
      "scope": "tag",
      "path": "/tag/vuepress/",
      "pageKeys": [
        "v-b07f4888",
        "v-4638da08",
        "v-7832e8be",
        "v-a250cabc",
        "v-901caf40",
        "v-2e581418",
        "v-7de893c4",
        "v-c729b8a8",
        "v-186168f2",
        "v-47eedbf0",
        "v-69e22104"
      ]
    },
    "markdown": {
      "key": "markdown",
      "scope": "tag",
      "path": "/tag/markdown/",
      "pageKeys": [
        "v-a250cabc",
        "v-901caf40",
        "v-7de893c4",
        "v-c729b8a8"
      ]
    },
    "theme": {
      "key": "theme",
      "scope": "tag",
      "path": "/tag/theme/",
      "pageKeys": [
        "v-2e581418",
        "v-186168f2",
        "v-47eedbf0",
        "v-69e22104"
      ]
    },
    "blog": {
      "key": "blog",
      "scope": "tag",
      "path": "/tag/blog/",
      "pageKeys": [
        "v-2e581418",
        "v-186168f2",
        "v-47eedbf0",
        "v-69e22104"
      ]
    }
  }
}